Repository ChartBoost/chartboost-mediation-unity-sdk, pull requests merged in 2023-09, with the labels that each got.

#167 Chartboost Mediation Unity SDK 4.5.0 into Develop
  com.chartboost.mediation.demo/Assets/Demo/Demo.cs
  com.chartboost.mediation.demo/ProjectSettings/ProjectSettings.asset
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/AdWrapper.kt
  com.chartboost.mediation/Editor/BuildTools/ChartboostMediationPreprocessor.cs
  com.chartboost.mediation/Editor/ChartboostMediationSettingsEditor.cs
  com.chartboost.mediation/Runtime/ChartboostMediationSettings.cs
  com.chartboost.mediation/Runtime/FullScreen/ChartboostMediationFullScreenBase.cs
  com.chartboost.mediation/Runtime/FullScreen/Interstitial/ChartboostMediationInterstitialAndroid.cs
  com.chartboost.mediation/Runtime/FullScreen/Rewarded/ChartboostMediationRewardedAndroid.cs
  com.chartboost.mediation/Runtime/FullScreen/Rewarded/ChartboostMediationRewardedBase.cs
  com.chartboost.mediation/Runtime/Platforms/Android/ChartboostMediationAndroid.cs
  com.chartboost.mediation/Runtime/Platforms/ChartboostMediationExternal.cs
  com.chartboost.mediation/Runtime/Plugins/Android/chartboost-mediation-android-bridge.jar
Labels: release

#169 [HB-6464] Updating EDM to version 1.2.177
  com.chartboost.mediation.demo/GooglePackages/com.google.external-dependency-manager-1.2.171.tgz.meta
  com.chartboost.mediation.demo/GooglePackages/com.google.external-dependency-manager-1.2.175.tgz
  com.chartboost.mediation.demo/GooglePackages/com.google.external-dependency-manager-1.2.177.tgz
  com.chartboost.mediation.demo/Packages/manifest.json
Labels: bugfix

#166 [HB-6379] Include Adaptive Banner Support in Unity
  com.chartboost.mediation.demo/Assets/Demo/Demo.cs
  com.chartboost.mediation.demo/Assets/Demo/Demo.unity
  com.chartboost.mediation.demo/ProjectSettings/ProjectSettings.asset
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/AdStore.kt
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/AdWrapper.kt
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/BannerAdWrapper.kt
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/BannerLayout.kt
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/ChartboostMediationBannerViewListener.kt
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/IBannerDragListener.kt
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/UnityBridge.kt
  com.chartboost.mediation/Editor/ChartboostMediationUnityBannerAdEditor.cs
  com.chartboost.mediation/Editor/ChartboostMediationUnityBannerAdEditor.cs.meta
  com.chartboost.mediation/Runtime/AdFormats/Banner.meta
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewAndroid.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewAndroid.cs.meta
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewBase.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewBase.cs.meta
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewIOS.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewIOS.cs.meta
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewUnsupported.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewUnsupported.cs.meta
  com.chartboost.mediation/Runtime/AdFormats/Banner/IChartboostMediationBannerView.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/IChartboostMediationBannerView.cs.meta
  com.chartboost.mediation/Runtime/AdFormats/Banner/Unity.meta
  com.chartboost.mediation/Runtime/AdFormats/Banner/Unity/ChartboostMediationUnityBannerAd.Creator.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/Unity/ChartboostMediationUnityBannerAd.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/Unity/ChartboostMediationUnityBannerAd.cs.meta
  com.chartboost.mediation/Runtime/Banner/ChartboostMediationBannerAd.cs
  com.chartboost.mediation/Runtime/Banner/ChartboostMediationBannerAdSize.cs
  com.chartboost.mediation/Runtime/Banner/ChartboostMediationBannerAdSize.cs.meta
  com.chartboost.mediation/Runtime/Banner/ChartboostMediationBannerAndroid.cs
  com.chartboost.mediation/Runtime/Banner/ChartboostMediationBannerIOS.cs
  com.chartboost.mediation/Runtime/Banner/IChartboostMediationBannerEvents.cs
  com.chartboost.mediation/Runtime/ChartboostMediation.cs
  com.chartboost.mediation/Runtime/Data/Metrics.cs
  com.chartboost.mediation/Runtime/Events/EventProcessor.cs
  com.chartboost.mediation/Runtime/Platforms/Android/ChartboostMediationAndroid.Callbacks.cs
  com.chartboost.mediation/Runtime/Platforms/Android/ChartboostMediationAndroid.cs
  com.chartboost.mediation/Runtime/Platforms/ChartboostMediationExternal.cs
  com.chartboost.mediation/Runtime/Platforms/ChartboostMediationUnsupported.cs
  com.chartboost.mediation/Runtime/Platforms/IOS/ChartboostMediationIOS.Callbacks.cs
  com.chartboost.mediation/Runtime/Platforms/IOS/ChartboostMediationIOS.cs
  com.chartboost.mediation/Runtime/Plugins/Android/chartboost-mediation-android-bridge.jar
  com.chartboost.mediation/Runtime/Plugins/iOS/ChartboostMediationBannerAdWrapper.h
  com.chartboost.mediation/Runtime/Plugins/iOS/ChartboostMediationBannerAdWrapper.m
  com.chartboost.mediation/Runtime/Plugins/iOS/ChartboostMediationUnityBridge.mm
  com.chartboost.mediation/Runtime/Requests/ChartboostMediationBannerAdLoadRequest.cs
  com.chartboost.mediation/Runtime/Requests/ChartboostMediationBannerAdLoadRequest.cs.meta
  com.chartboost.mediation/Runtime/Requests/ChartboostMediationBannerAdLoadResult.cs
  com.chartboost.mediation/Runtime/Requests/ChartboostMediationBannerAdLoadResult.cs.meta
  com.chartboost.mediation/Runtime/Requests/ChartboostMediationFullscreenAdLoadResult.cs
  com.chartboost.mediation/Runtime/Utilities/AndroidAdStore.cs
  com.chartboost.mediation/Runtime/Utilities/CacheManager.cs
  com.chartboost.mediation/Runtime/Utilities/ChartboostMediationConverters.cs
  com.chartboost.mediation/Runtime/Utilities/ChartboostMediationExtensions.cs
  com.chartboost.mediation/Runtime/Utilities/ChartboostMediationExtensions.cs.meta
  com.chartboost.mediation/Runtime/Utilities/ChartboostMediationUtils.cs
  com.chartboost.mediation/Runtime/Utilities/Constants.cs
  com.chartboost.mediation/Runtime/Utilities/Constants.cs.meta
  com.chartboost.mediation/Runtime/Utilities/Logger.cs
Labels: enhancement, api refactoring
