Repository ChartBoost/chartboost-mediation-unity-sdk, pull requests merged in 2023-10, with the labels that each got.

#179 [HB-6572] Always Keep the BannerAd within the Safe Area
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/BannerLayout.kt
  com.chartboost.mediation/Runtime/AdFormats/Banner/Unity/ChartboostMediationUnityBannerAd.Creator.cs
  com.chartboost.mediation/Runtime/Plugins/Android/chartboost-mediation-android-bridge.jar
  com.chartboost.mediation/Runtime/Plugins/iOS/ChartboostMediationBannerAdWrapper.m
Labels: bugfix

#182 [HB-6583] Chartboost Mediation Unsupported Should Call `DidStart` with Error
  com.chartboost.mediation/Runtime/Platforms/ChartboostMediationUnsupported.cs
Labels: enhancement, bugfix

#191 [HB-6570] Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation

#192 [HB-6541][HB-6646] Fix Calling Deprecated Functions And Features in All Platforms
  com.chartboost.mediation.demo/ProjectSettings/ProjectSettings.asset
  com.chartboost.mediation/Documentation/images/create-unity-banner-ad.png.meta
  com.chartboost.mediation/Runtime/Banner/ChartboostMediationBannerIOS.cs
  com.chartboost.mediation/Runtime/Banner/IChartboostMediationBannerEvents.cs
  com.chartboost.mediation/Runtime/ChartboostMediation.cs
  com.chartboost.mediation/Runtime/FullScreen/ChartboostMediationFullScreenBase.cs
  com.chartboost.mediation/Runtime/FullScreen/Interstitial/ChartboostMediationInterstitialAndroid.cs
  com.chartboost.mediation/Runtime/FullScreen/Interstitial/ChartboostMediationInterstitialIOS.cs
  com.chartboost.mediation/Runtime/FullScreen/Interstitial/IChartboostMediationInterstitialEvents.cs
  com.chartboost.mediation/Runtime/FullScreen/Rewarded/ChartboostMediationRewardedAndroid.cs
  com.chartboost.mediation/Runtime/FullScreen/Rewarded/ChartboostMediationRewardedBase.cs
  com.chartboost.mediation/Runtime/FullScreen/Rewarded/ChartboostMediationRewardedIOS.cs
  com.chartboost.mediation/Runtime/FullScreen/Rewarded/IChartboostMediationRewardedEvents.cs
  com.chartboost.mediation/Runtime/Platforms/Android/ChartboostMediationAndroid.Callbacks.cs
  com.chartboost.mediation/Runtime/Platforms/Android/ChartboostMediationAndroid.Legacy.cs
  com.chartboost.mediation/Runtime/Platforms/Android/ChartboostMediationAndroid.cs
  com.chartboost.mediation/Runtime/Platforms/ChartboostMediationExternal.cs
  com.chartboost.mediation/Runtime/Platforms/ChartboostMediationUnsupported.cs
  com.chartboost.mediation/Runtime/Platforms/IOS/ChartboostMediationIOS.Callbacks.cs
  com.chartboost.mediation/Runtime/Platforms/IOS/ChartboostMediationIOS.Legacy.cs
  com.chartboost.mediation/Runtime/Platforms/IOS/ChartboostMediationIOS.cs
Labels: bugfix

#194 [HB-6639] Adds `ContainerSize` to BannerView API
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/BannerAdWrapper.kt
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerSize.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewAndroid.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewBase.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewIOS.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/ChartboostMediationBannerViewUnsupported.cs
  com.chartboost.mediation/Runtime/AdFormats/Banner/IChartboostMediationBannerView.cs
  com.chartboost.mediation/Runtime/Plugins/Android/chartboost-mediation-android-bridge.jar
  com.chartboost.mediation/Runtime/Plugins/iOS/ChartboostMediationUnityBridge.mm
  com.chartboost.mediation/Runtime/Utilities/AndroidExtensions.cs
Labels: api refactoring

#196 [HB-6693] Banner Ads Loaded Using `BannerView` API Always Loads at `top-left` Irrespective of Whatever `screenLocation` is Selected
  com.chartboost.mediation/Android~/chartboost-mediation-android-bridge/src/main/java/com/chartboost/mediation/unity/BannerAdWrapper.kt
  com.chartboost.mediation/Runtime/Plugins/Android/chartboost-mediation-android-bridge.jar
Labels: bugfix

#197 [HB-6543] Add API to Allow Game Publishers to Specify the `ChartboostMediationSettings` Object
  com.chartboost.mediation/Editor/ChartboostMediationSettingsEditor.cs
  com.chartboost.mediation/Editor/ChartboostMediationSettingsEditor.cs.meta
  com.chartboost.mediation/Editor/Settings/SettingsWindow.cs
  com.chartboost.mediation/Runtime/ChartboostMediationSettings.cs
Labels: enhancement, api refactoring

#198 Platform Fix for `ChartboostMediationBannerAdWrapper.h`
  com.chartboost.mediation/Runtime/Plugins/iOS/ChartboostMediationBannerAdWrapper.h.meta
Labels: bugfix
